### ISSUE TITLE
[Security] Workflow reviewdog.yml is using vulnerable action tsuyoshicho/action-textlint

### ISSUE THREAD

**Issue by Freakston** [drumath2237/zenn-articles#44]
The workflow reviewdog.yml is referencing action tsuyoshicho/action-textlint using references v1. However this reference is missing the commit [e6ad991bb76bebe3d7a7929e5c59e221950a0098](https://github.com/tsuyoshicho/action-textlint/commits/e6ad991bb76bebe3d7a7929e5c59e221950a0098) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by drumath2237** [comment]
@Freakston Thank you for reporting. Now this repo is using tsuyoshicho/action-textlint **v3**.
